### PR TITLE
fix: add tabindex to donate in navbar

### PR DESCRIPTION
**Pull request by Yash-Singh1**
Adds a `tabindex` to navigation bar for accessibility purposes.

### CODE REVIEW

**Comment by nzakas** [comment]
Can you explain why this is needed? You can already tab to the link.

**Comment by Yash-Singh1** [comment]
> Can you explain why this is needed? You can already tab to the link.

I couldn't tab to it on my computer, Chrome 92, Ubuntu 20.

**Comment by nzakas** [comment]
I've tried in Firefox, Chrome, and Edge on Windows and can't reproduce.

**Comment by Yash-Singh1** [comment]
Oh, it turns out the `Donate` button gets tabbed onto before the rest of the links.

ezgif com-gif-maker (6)

**Pull request closed without merging**
