### PR TITLE
chore: Remove CSS files

### PR DESCRIPTION
**Pull request by nzakas**
Removing the generated CSS files from the repo.

It looks like we already had these files in `.gitignore`: https://github.com/eslint/new.eslint.org/blob/main/.gitignore#L13

Maybe we just forgot to remove them?

### CODE REVIEW

**Review by btmills — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]
LGTM

**Comment by snitin315** [comment]
Deploy preview is not for English translation 🤔

**Comment by btmills** [comment]
> Deploy preview is not for English translation 🤔

Did you also look at the `new-eslint` deploy preview in the [first comment](https://github.com/eslint/new.eslint.org/pull/180#issuecomment-1079550461)?

**Comment by snitin315** [comment]
Oh! we have two different deploy comments. That's nice.

**Comment by nzakas** [comment]
Yeah, all of the international sites run off the same repo, so it will generate a deploy preview for each of them. :)

**Pull request merged**
